### ISSUE TITLE
panicked at 'The reclaimed file 1 is not a active file'

### ISSUE THREAD

**Issue by w41ter** [huachaohuang/photondb#287]
```
thread 'tokio-runtime-worker' panicked at 'The reclaimed file 19 is not a active file', photondb/src/page_store/jobs/flush.rs:223:17                                                stack backtrace:                                                                                                                                                                       0: rust_begin_unwind                                                                                                                                                                          at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:556:5                                                                                     1: core::panicking::panic_fmt                                                                                                                                                                 at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panicking.rs:142:14
   2: photondb::page_store::jobs::flush::assert_files_are_deletable                                                                                                                              at ./src/page_store/jobs/flush.rs:223:17                                                                                                                                  3: photondb::page_store::jobs::flush::drain_obsoleted_files                                                                                                                                   at ./src/page_store/jobs/flush.rs:203:5                                                                                                                                   4: photondb::page_store::jobs::flush::FlushCtx<E>::flush::{{closure}}
             at ./src/page_store/jobs/flush.rs:91:31
[2022-11-16T12:46:57Z INFO  photondb::page_store::write_buffer] Seal write buffer 23, allocated 1036608 bytes, usage 0.98858642578125                                               [2022-11-16T12:46:57Z DEBUG photondb::page_store::version] Install new buffer 24, buffer set range 22..25
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   6: photondb::page_store::jobs::flush::FlushCtx<E>::run::{{closure}}
             at ./src/page_store/jobs/flush.rs:67:62
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/future/mod.rs:91:19
   8: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:184:17
   9: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/loom/std/unsafe_cell.rs:14:9
  10: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/core.rs:174:13
  11: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.21.2/src/runtime/task/harness.rs:480:19
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/core/src/panic/unwind_safe.rs:271:9
  13: std::panicking::try::do_call
             at /rustc/8ce3204af9463db3192ea1eb31c45c2f6d4b5ae6/library/std/src/panicking.rs:464:41
```

Ref https://github.com/photondb/photondb/actions/runs/3479396500/jobs/5817890722

**Comment by w41ter** [comment]
The reason is similar to #244
